[package]
name = "keycloak"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
base64 = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
